### ISSUE TITLE
First test case is problematic

### ISSUE THREAD

**Issue by rossmcdonald** [rossmcdonald/bearcub#1]
Regarding the first test case:

```
--- FAIL: TestRequestReplaceVariables (0.00s)
        variable_test.go:417: Test Should handle undefined variables, expecting:
                GET / HTTP/1.1
                Host: {host}
                User-Agent: Fake
                Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
                Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
                Accept-Encoding: gzip,deflate
                Accept-Language: en-us,en;q=0.5
                Keep-Alive: 300
                Proxy-Connection: keep-alive


                Got:
                GET / HTTP/1.1
                Host: www.techcrunch.com
                User-Agent: Fake
                Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
                Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
                Accept-Encoding: gzip,deflate
                Accept-Language: en-us,en;q=0.5
                Keep-Alive: 300
                Proxy-Connection: keep-alive
```

Since `Host` is being set by the test case, it will always default to `www.techcrunch.com` instead of `{host}`, which is what the test expects. There are two ways around this:

* Removing the `Host` portion of the request declaration, ie removing this (L60):

   ```
   Host:  "www.techcrunch.com",
   ```

* Overriding the `Host` in the replace function with a `req.Host = ""`, which opts to use the URL host instead of the declared one.

So I can either modify the test case or the way the function handles the http.Request `Host` field.
